---
# ansible-role-repo-epel/tasks/main.yml
# Author: MTO 
# Description: Task for installing the EPEL Repo on RedHat or Centos.
#
- name: Check if EPEL repo is already configured.
  stat: path="{{ repo_epel_file_path }}"
  register: repo_epel_file_result

- name: Install EPEL repo.
  yum:
    name: "{{ repo_epel_url }}"
    state: present
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10
  when: not repo_epel_file_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ repo_epel_gpg_key_url }}"
    state: present
  when: not repo_epel_file_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"